/* const $list = {
    Beginner: 
        ["HELLO", "TEST", "DOG"],
    Easy:
        ["GIRAFFE", "APPLE", "BANANA"]
    
} */

const $list = {
    Beginner: [
      "dog",
      "cat",
      "hat",
      "sun",
      "fun",
      "car",
      "star",
      "ball",
      "wall",
      "fall",
      "tree",
      "bee",
      "sea",
      "me",
      "we",
      "he",
      "she",
      "key",
      "see",
      "three",
      "four",
      "five",
      "six",
      "seven",
      "eight",
      "nine",
      "ten",
      "red",
      "blue",
      "green",
      "yellow"
    ],
    Easy: [
      "book",
      "look",
      "cook",
      "nose",
      "rainbow",
      "mouth",
      "ears",
      "roof",
      "loop",
      "pool",
      "moon",
      "spoon",
      "noon",
      "dune",
      "tune",
      "soon",
      "boon",
      "June",
      "boon",
      "room",
      "zoom",
      "broom",
      "boom",
      "groom",
      "school",
      "cool",
      "rule",
      "fuel",
      "junebug",
      "moonbeam",
      "butterfly"
    ],
    Medium: [
      "I see a cat.",
      "The dog barks.",
      "Mom bakes a cake.",
      "Dad mows the lawn.",
      "I love ice cream.",
      "The sun is shining.",
      "I go to school.",
      "I like to play.",
      "I have a best friend.",
      "I ride my bike.",
      "I have a pet fish.",
      "I brush my teeth.",
      "I play with blocks.",
      "I draw with crayons.",
      "I sing a song.",
      "I dance to music.",
      "I catch a ball.",
      "I jump rope.",
      "I play with toys.",
      "I swim in the pool.",
      "I go on a hike.",
      "I play outside.",
      "I read a book.",
      "I watch TV.",
      "I eat breakfast.",
      "I drink milk.",
      "I have a nap.",
      "I play with my cat.",
      "I help with chores.",
      "I listen to music.",
      "I learn new things."
    ],
    Hard: [
      "I love my family.",
      "I have a great teacher.",
      "I like to play games.",
      "I enjoy playing sports.",
      "I have many friends.",
      "I go on adventures.",
      "I read books every day.",
      "I learn new things at school.",
      "I play with my pets.",
      "I watch movies with my family.",
      "I like to draw pictures.",
      "I go to the park.",
      "I like to explore nature.",
      "I help with cooking.",
      "I listen to music and dance.",
      "I love my bedroom.",
      "I visit my grandparents.",
      "I swim in the ocean.",
      "I like to learn new skills.",
      "I go on bike rides.",
      "I love to travel.",
      "I take care of my pets.",
      "I do well in school.",
      "I love to play with my friends.",
      "I play video games.",
      "I watch educational shows.",
      "I learn about science.",
      "I do well in art class.",
      "I like to try new foods.",
      "I play musical instruments.",
      ""
    ],
    Advanced: [
      "I go to school every day.",
      "I have a lot of hobbies.",
      "I like to play with friends.",
      "I learn new things every day.",
      "I love spending time with family.",
      "I like to go on trips.",
      "I watch educational shows.",
      "I love reading books.",
      "I like to play sports.",
      "I have a pet dog.",
      "I enjoy playing video games.",
      "I do well in school.",
      "I help with chores at home.",
      "I like to try new foods.",
      "I go to the park with friends.",
      "I love listening to music.",
      "I play musical instruments.",
      "I like to learn about science.",
      "I enjoy doing art projects.",
      "I like to be active.",
      "I love animals.",
      "I like to explore new places.",
      "I love learning new skills.",
      "I have a fun summer vacation.",
      "I go to the library.",
      "I love spending time outdoors.",
      "I like to play with my pets.",
      "I watch exciting movies.",
      "I like to learn about history.",
      "I go to the beach.",
      ""
    ]
  }